services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    networks:
      - app-net

  frontend:
    build: ./frontend
    ports:
      - "8080:80"   # use 8080 to avoid any dev server leftovers on 3000
    depends_on:
      - backend
    networks:
      - app-net

networks:
  app-net:
